### ISSUE TITLE
Safari 13 disables TamperMonkey -- any way to recover settings?

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#75] opened 2019-09-21 00:12 UTC
I made the terrible mistake of allowing the system to upgrade Safari to version 13. I did not know that would disable TamperMonkey.

I think I have to move to a different browser for FFandS. Is there a way for me to transfer my settings. I don't think it is feasible to downgrade to Safari 12 to save a backup.

Thanks,
John

**Comment by johnpane** [comment] 2019-09-21 00:12
Even knowing where the settings are stored could possibly help me recover them.

**Comment by soufianesakhi** [comment] 2019-09-21 13:20
Perhaps you can be inspired by the way it is store for Tampermonkey on Google Chrome: https://stackoverflow.com/a/16829262/6365858, but I didn't find anything for Safari (maybe it uses a different database / mechanism to store the script data). I can't assist you further concerning Safari because I don't have a Mac.

If you do find and recover the settings for the Feedly Filtering and Sorting script, you could try Tampermonkey for Google Chrome and paste the data in this tab:
![y7afj](https://user-images.githubusercontent.com/17222854/65373829-d8a40d80-dc82-11e9-8d32-07603192adf6.png).

I'm going to close the issue as it's not really caused by the script itself.

**Closed by soufianesakhi** 2019-09-21 13:20 UTC

**Comment by soufianesakhi** [comment] 2019-09-21 13:24
I found this link, maybe you could install the tampermonkey extension manually and copy the script's data as shown above ? https://georgegarside.com/blog/macos/install-any-safari-extension-macos-mojave/

**Comment by johnpane** [comment] 2019-09-21 13:27
Thank you kindly for trying to assist. I did see the georgegarside.com blog but Safari 13 does not support that method. (And sorry for filling an issue to ask you -- I didn't know another way to contact you).
