### ISSUE TITLE
Problem with sorting and then clicking on the item

### ISSUE THREAD

**Issue by ms6666** [soufianesakhi/feedly-filtering-and-sorting#110] opened 2021-07-20 12:01 UTC
With the last changes sorting work again, but when i am in "article view" and sort by a-z, sorting works, but when i click on a item it expand, but on the old position without sorting, so the navigation with j/k-keys isnt possible

**Comment by soufianesakhi** [comment] 2021-07-20 20:25
Can you check if the issue is fixed in the latest version?

**Comment by ms6666** [comment] 2021-07-24 22:29
Sorry for the late reply.
Testet it again with Chrom-Plugin Version 3.21.5 and also with Userscript, same Problem.
I made some Screenshots, first is the original article-view, then i go into "feedly-filtering-and-sorting"-menu and activate sort a-z, after that the Feed is sorted by a-z, but then when i click on one of the item the item opens, but the position of the  item is another one and so i cant use j/k to jump to the next or previous item.

![1 Original](https://user-images.githubusercontent.com/32864681/126882295-e07337ad-b973-4111-a3d8-fc6260bd434f.png)
![2 Activate Sort a-z](https://user-images.githubusercontent.com/32864681/126882342-1547d559-00ae-487c-a09c-f7493babbfe0.png)
![3 Sort a-z](https://user-images.githubusercontent.com/32864681/126882301-aa5170b4-3f1a-4e37-8577-bcbc1ffc53d0.png)
![4 Open Item](https://user-images.githubusercontent.com/32864681/126882428-b664dc07-ddcb-48e9-9549-d09d8012b469.png)

**Closed** 2021-07-29 23:08 UTC
