### ISSUE TITLE
Extreme memory use

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#76] opened 2019-10-12 20:24 UTC
It seems like every time feedly updates, there is some operation that uses huge amounts of memory and 100% CPU. This lasts for hours but eventually settles down and everything starts acting normally. Since I have started using FFandS this has happened about a dozen times.

<img width="321" alt="Screen Shot 2019-10-12 at 16 21 30" src="https://user-images.githubusercontent.com/14841761/66707333-c3b01c80-ed0c-11e9-9aae-397e0f6c7958.png">

**Comment by johnpane** [comment] 2019-10-12 20:25
I am running FFandS in Chrome, so the resource use is shown as Chrome in the screen shot. This also happened when I was running FFandS in Safari. (I switched to Chrome because TamperMonkey is no longer available for Safari 13.)

**Comment by soufianesakhi** [comment] 2019-10-16 16:45
Do you have "Auto load all unread articles" enabled by any chance ? If there are 1000+ unread articles, there may be some freezes.
If not, can you disable the script and reload the page when you experience the same processing spike ? Does the CPU / memory usage go back to normal ?

You can also try the [extension ](https://chrome.google.com/webstore/detail/feedly-filtering-and-sort/anknmaofbemimfabppdffklbfiecikgo)since you are using chrome (you can export / import the settings)

**Comment by johnpane** [comment] 2019-10-16 17:03
I do not have "Auto load all unread articles" enabled.

If I disable the script, reload (or restart the browser completely) and restart, the same processing spike occurs. 

Could it be related to the Duplicates Filtering option, "Enable cross checking with persistence up to: 1 days" ?

**Comment by johnpane** [comment] 2019-10-16 17:15
I have turned off that option, hoping that might solve the problem.

**Comment by soufianesakhi** [comment] 2019-10-16 17:19
You had the same processing spike when you disabled the script? If so, maybe it's caused by another extension.

**Comment by johnpane** [comment] 2019-10-16 17:27
I'm sorry, I misunderstood your question. If the script is disabled there is no CPU load. The problem comes back when I turn the script back on.

**Comment by soufianesakhi** [comment] 2019-10-16 17:56
When you experience the process spike, can you check the console logs (Command + Option + J on Mac)? Are there any repeated logs or errors from the script?

**Comment by johnpane** [comment] 2019-10-16 18:02
Ok, I will try that next time it happens.

Do you agree the Duplicate Filtering cross checking could have been a possible cause?

**Comment by soufianesakhi** [comment] 2019-10-19 23:30
I will close this issue for the time being. Feel free to reopen it when you have any news regarding this issue.

**Closed by soufianesakhi** 2019-10-19 23:30 UTC
