### ISSUE TITLE
Freeze on "Today" view

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#26] opened 2017-09-15 18:08 UTC
Hello,

When using the extension (on Chrome) and opening the "Today" view, it freezes and I'm forced to close the tab. It does that even when disabling the loading of all articles, batch, sorting and basically everything. Only disabling the extension stops the freeze. Bug ?

**Comment by soufianesakhi** [comment] 2017-09-15 18:13
I think it's caused by the sorting. The Today view is not really supported for sorting, I will fix it.

**Comment by soufianesakhi** [comment] 2017-09-16 16:55
Fixed in v3.4.0

**Closed by soufianesakhi** 2017-09-16 16:55 UTC
